// <auto-generated />
using System;
using EmployeeManagement.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManagement.Migrations
{
    [DbContext(typeof(EmployeesDbContext))]
    [Migration("20210622145512_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeManagement.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Pesel")
                        .IsUnique();

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            BirthDate = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tony",
                            Pesel = "54092397111",
                            RegistrationNumber = "00000001",
                            Sex = 0,
                            Surname = "Stark"
                        },
                        new
                        {
                            EmployeeId = 2,
                            BirthDate = new DateTime(1988, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bruce",
                            Pesel = "90102826611",
                            RegistrationNumber = "00000002",
                            Sex = 0,
                            Surname = "Banner"
                        },
                        new
                        {
                            EmployeeId = 3,
                            BirthDate = new DateTime(1975, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sue",
                            Pesel = "38100948214",
                            RegistrationNumber = "00000003",
                            Sex = 1,
                            Surname = "Storm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
